### ISSUE TITLE
ARN parsing is too strict on resources

### ISSUE THREAD

**Issue by dacut** [johnstonskj/rust-aws-arn#2]
I have a CloudWatch alarm named `Production:LB:High4xx`, which has an ARN in the form: `arn:aws:cloudwatch:us-west-1:123456789012:alarm:Production:LB:High4xx`. Note the multiple `:` after the account id.

This pattern doesn't satisfy either `Resource::TypedId` or `Resource::QTypedId` variants, so code like this fails:
```rust
ARN::from_str("arn:aws:cloudwatch:us-west-2:123456789012:alarm:Production:LB:High4xx").unwrap()
```

I'm not aware of any particular rules on the resource section of an ARN here; unfortunately, IIRC the original (AWS internal) Aspen spec left it up to the services teams, and CloudWatch made some particularly bad choices here with regard to separators and user-defined names. There are also cases (notably in S3 paths) where double slashes are allowed and needed (though this seems to work ok).

You might consider just letting the ':' codepath go similarly to the '/' codepath, or even abandoning validating the resource part entirely (beyond that "it's ASCII").

**Comment by johnstonskj** [comment]
Thanks! I'll take a look.

**Comment by johnstonskj** [comment]
Have undertaken a major refactor, removing the old Resource enum and adding new Identifier and ResourceIdentifier types. I specifically added a test case for your CloudWatch example as well.

https://github.com/johnstonskj/rust-aws-arn/blob/8f9d57fbf3d7ed1ba9ced3ade4bfd7b96affb662/tests/test_arn.rs#L38

**Comment by dacut** [comment]
I read through the latest, and it definitely solves this issue. Thanks! I'll close this out here.
